### ISSUE TITLE
docs require

### ISSUE THREAD

**Issue by morenoh149** [jgallen23/node-ga#7]
so do you do `var ga = require('ga')` or how does this work?

**Comment by OKNoah** [comment]
@jgallen23 @morenoh149 Happy 1 year anniversary to this issue.

**Comment by preetampvp** [comment]
// usage that worked for me.
var GoogleAnalytics = require('ga');
var host = "domain.com";
var ga = new GoogleAnalytics("UA-code", host);

**Comment by OKNoah** [comment]
@jgallen23 @morenoh149 Slightly belated 3 year anniversary of this issue :)

**Comment by nswbmw** [comment]
6 years now, haha

**Comment by morenoh149** [comment]
I made this issue before I was comfortable reading source files.
Usage is shown here https://github.com/jgallen23/node-ga/blob/master/tests/ga.test.js#L1
```
var GoogleAnalytics = require('../lib/ga');
```
if you installed via npm its probably like
```
import GoogleAnalytics from "ga";
```
